fieldLayouts:
  11f52ba8-9f70-406e-8f3b-ef83b50f47ed:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            autofocus: false
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            required: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\EntryTitleField
            warning: null
            width: 100
          -
            fieldUid: c86f3bea-f15e-45ea-bcb1-d15271050e14
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 50
          -
            fieldUid: af0d375d-ceb0-44a2-843b-89da565833bb
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 50
        name: Details
        sortOrder: 1
handle: person
hasTitleField: false
name: Person
section: 10b06272-99be-4a67-8661-d2c4e5064f18
sortOrder: 1
titleFormat: '{firstName} {lastName}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
