handle: contributorTypes
name: 'Contributor Types'
siteSettings:
  1eac5e05-6bb4-47c3-ad67-d9f6c170d55c:
    hasUrls: true
    template: ''
    uriFormat: 'contributor-types/{slug}'
structure:
  maxLevels: null
  uid: 7034390c-c7f7-4327-b6f0-19afd02b47d0
