fieldLayouts:
  81fc2028-8647-4dae-8fe6-e81f09e89937:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            autofocus: false
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            required: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\TitleField
            warning: null
            width: 100
          -
            fieldUid: d556dafd-a545-476a-85d0-57b655e9f624
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
handle: productCategories
name: 'Product Categories'
siteSettings:
  1eac5e05-6bb4-47c3-ad67-d9f6c170d55c:
    hasUrls: true
    template: null
    uriFormat: 'product-categories/{slug}'
structure:
  maxLevels: null
  uid: 028cc721-5f9f-4dea-90e7-d620d429ff4d
