categoryGroups:
  374ba7ad-f9f4-4dd9-9fcf-71db673a5dc3:
    handle: productCategories
    name: 'Product Categories'
    siteSettings:
      1eac5e05-6bb4-47c3-ad67-d9f6c170d55c:
        hasUrls: true
        template: ''
        uriFormat: 'product-categories/{slug}'
    structure:
      maxLevels: null
      uid: 028cc721-5f9f-4dea-90e7-d620d429ff4d
dateModified: 1594224077
email:
  fromEmail: ret+reelizer@tinch.co
  fromName: Reelizer
  transportType: craft\mail\transportadapters\Sendmail
fieldGroups:
  1168b37e-e44d-4837-a7b4-be37f0db3647:
    name: People
  3183a522-3f08-4dbd-91b3-e38784120d7a:
    name: Common
  4f79aecd-c458-49fb-9f06-0510815918ed:
    name: Movies
  68b8bf74-05e0-459b-8f1d-fb4f5493990b:
    name: Products
fields:
  12029c4c-0ae4-48fb-8145-771f814dd949:
    contentColumnType: integer(10)
    fieldGroup: 4f79aecd-c458-49fb-9f06-0510815918ed
    handle: runtime
    instructions: ''
    name: Runtime
    searchable: true
    settings:
      decimals: 0
      defaultValue: null
      max: null
      min: '0'
      prefix: ''
      size: '4'
      suffix: ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Number
  1e26e8e7-3d94-411a-ae03-3afd8f7fd4c5:
    contentColumnType: datetime
    fieldGroup: 4f79aecd-c458-49fb-9f06-0510815918ed
    handle: releaseDate
    instructions: ''
    name: 'Release Date'
    searchable: true
    settings:
      minuteIncrement: '30'
      showDate: true
      showTime: false
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Date
  7822b855-6bb1-4898-b1a4-fcc827516403:
    contentColumnType: string
    fieldGroup: 68b8bf74-05e0-459b-8f1d-fb4f5493990b
    handle: subjects
    instructions: ''
    name: Subjects
    searchable: true
    settings:
      allowSelfRelations: ''
      limit: ''
      localizeRelations: false
      selectionLabel: ''
      source: null
      sources:
        - 'section:04feea2b-63cb-417d-936d-e76f76c80345'
        - 'section:10b06272-99be-4a67-8661-d2c4e5064f18'
      targetSiteId: null
      validateRelatedElements: ''
      viewMode: null
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Entries
  7c5f7163-94ca-463f-9658-2a71fa550d15:
    contentColumnType: text
    fieldGroup: 4f79aecd-c458-49fb-9f06-0510815918ed
    handle: originalName
    instructions: ''
    name: 'Original Name'
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  865b2841-55f6-4750-b1a3-b6d54b0b35ba:
    contentColumnType: string
    fieldGroup: 68b8bf74-05e0-459b-8f1d-fb4f5493990b
    handle: productCategories
    instructions: ''
    name: 'Product Categories'
    searchable: true
    settings:
      allowLimit: false
      allowMultipleSources: false
      allowSelfRelations: ''
      branchLimit: ''
      limit: null
      localizeRelations: false
      selectionLabel: ''
      source: 'group:374ba7ad-f9f4-4dd9-9fcf-71db673a5dc3'
      sources: '*'
      targetSiteId: null
      validateRelatedElements: ''
      viewMode: null
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Categories
  927ba68c-d30c-4453-a7e3-bda3e40affad:
    contentColumnType: text
    fieldGroup: 4f79aecd-c458-49fb-9f06-0510815918ed
    handle: tagline
    instructions: ''
    name: Tagline
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  954d573c-b1be-4342-aaaf-c72c8a2d6a60:
    contentColumnType: string
    fieldGroup: 3183a522-3f08-4dbd-91b3-e38784120d7a
    handle: images
    instructions: ''
    name: Images
    searchable: false
    settings:
      allowSelfRelations: ''
      allowedKinds:
        - image
      defaultUploadLocationSource: 'volume:063c95ee-112b-4ccf-adcb-3eb6a2831580'
      defaultUploadLocationSubpath: ''
      limit: ''
      localizeRelations: false
      restrictFiles: '1'
      selectionLabel: ''
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      singleUploadLocationSource: 'volume:063c95ee-112b-4ccf-adcb-3eb6a2831580'
      singleUploadLocationSubpath: '{section.handle}/{id}-{slug}'
      source: null
      sources: '*'
      targetSiteId: null
      useSingleFolder: true
      validateRelatedElements: ''
      viewMode: large
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  af0d375d-ceb0-44a2-843b-89da565833bb:
    contentColumnType: text
    fieldGroup: 1168b37e-e44d-4837-a7b4-be37f0db3647
    handle: lastName
    instructions: ''
    name: 'Last Name'
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  c86f3bea-f15e-45ea-bcb1-d15271050e14:
    contentColumnType: text
    fieldGroup: 1168b37e-e44d-4837-a7b4-be37f0db3647
    handle: firstName
    instructions: ''
    name: 'First Name'
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  e3fc8a10-0f46-4c75-81c7-fee43b0578b4:
    contentColumnType: integer(10)
    fieldGroup: 4f79aecd-c458-49fb-9f06-0510815918ed
    handle: releaseYear
    instructions: ''
    name: 'Release Year'
    searchable: true
    settings:
      decimals: 0
      defaultValue: null
      max: null
      min: '0'
      prefix: ''
      size: '4'
      suffix: ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Number
graphql:
  schemas:
    fb3be199-ee1e-4073-9808-2e7aa404470c:
      isPublic: true
      name: 'Public Schema'
plugins:
  aws-s3:
    edition: standard
    enabled: true
    schemaVersion: '1.2'
sections:
  04feea2b-63cb-417d-936d-e76f76c80345:
    enableVersioning: true
    entryTypes:
      2da3a35a-a3f0-43b7-9508-82b48e03fd5e:
        fieldLayouts:
          e6799fdf-e4ab-4607-8ae9-c780705be91f:
            tabs:
              -
                fields:
                  7c5f7163-94ca-463f-9658-2a71fa550d15:
                    required: false
                    sortOrder: 1
                name: Details
                sortOrder: 1
        handle: movie
        hasTitleField: true
        name: Movie
        sortOrder: 1
        titleFormat: ''
        titleLabel: Name
    handle: movies
    name: Movies
    previewTargets:
      -
        __assoc__:
          -
            - label
            - 'Primary entry page'
          -
            - urlFormat
            - '{url}'
          -
            - refresh
            - '1'
    propagationMethod: all
    siteSettings:
      1eac5e05-6bb4-47c3-ad67-d9f6c170d55c:
        enabledByDefault: true
        hasUrls: true
        template: ''
        uriFormat: 'movies/{slug}'
    type: channel
  10b06272-99be-4a67-8661-d2c4e5064f18:
    enableVersioning: true
    entryTypes:
      3361190f-4808-4be5-b215-38bf94edd9a2:
        fieldLayouts:
          11f52ba8-9f70-406e-8f3b-ef83b50f47ed:
            tabs:
              -
                fields:
                  af0d375d-ceb0-44a2-843b-89da565833bb:
                    required: false
                    sortOrder: 2
                  c86f3bea-f15e-45ea-bcb1-d15271050e14:
                    required: false
                    sortOrder: 1
                name: Details
                sortOrder: 1
        handle: person
        hasTitleField: true
        name: Person
        sortOrder: 1
        titleFormat: ''
        titleLabel: Title
    handle: people
    name: People
    previewTargets:
      -
        __assoc__:
          -
            - label
            - 'Primary entry page'
          -
            - urlFormat
            - '{url}'
          -
            - refresh
            - '1'
    propagationMethod: all
    siteSettings:
      1eac5e05-6bb4-47c3-ad67-d9f6c170d55c:
        enabledByDefault: true
        hasUrls: true
        template: ''
        uriFormat: 'people/{slug}'
    type: channel
  61807da0-a442-4685-bfcc-09bf44bb182c:
    enableVersioning: true
    entryTypes:
      1df00b0a-8c79-4001-8d47-46e45ea01067:
        handle: article
        hasTitleField: true
        name: Article
        sortOrder: 1
        titleFormat: ''
        titleLabel: Title
    handle: articles
    name: Articles
    previewTargets:
      -
        __assoc__:
          -
            - label
            - 'Primary entry page'
          -
            - urlFormat
            - '{url}'
          -
            - refresh
            - '1'
    propagationMethod: all
    siteSettings:
      1eac5e05-6bb4-47c3-ad67-d9f6c170d55c:
        enabledByDefault: true
        hasUrls: true
        template: ''
        uriFormat: 'articles/{slug}'
    type: channel
  826e2e4b-5fe0-4878-a177-d072ecf1c02d:
    enableVersioning: true
    entryTypes:
      78e52e42-baf9-4893-b876-6aee344106db:
        fieldLayouts:
          312849ed-4610-435a-8850-df672ad05cef:
            tabs:
              -
                fields:
                  7822b855-6bb1-4898-b1a4-fcc827516403:
                    required: false
                    sortOrder: 3
                  865b2841-55f6-4750-b1a3-b6d54b0b35ba:
                    required: true
                    sortOrder: 1
                  954d573c-b1be-4342-aaaf-c72c8a2d6a60:
                    required: true
                    sortOrder: 2
                name: Details
                sortOrder: 1
        handle: product
        hasTitleField: true
        name: Product
        sortOrder: 1
        titleFormat: ''
        titleLabel: Title
    handle: products
    name: Products
    previewTargets:
      -
        __assoc__:
          -
            - label
            - 'Primary entry page'
          -
            - urlFormat
            - '{url}'
          -
            - refresh
            - '1'
    propagationMethod: all
    siteSettings:
      1eac5e05-6bb4-47c3-ad67-d9f6c170d55c:
        enabledByDefault: true
        hasUrls: true
        template: ''
        uriFormat: 'products/{slug}'
    type: channel
siteGroups:
  1a0c3718-ac66-4862-9ee6-4d676908d3c1:
    name: Reelizer
sites:
  1eac5e05-6bb4-47c3-ad67-d9f6c170d55c:
    baseUrl: $DEFAULT_SITE_URL
    handle: default
    hasUrls: true
    language: en-US
    name: Reelizer
    primary: true
    siteGroup: 1a0c3718-ac66-4862-9ee6-4d676908d3c1
    sortOrder: 1
system:
  edition: pro
  live: true
  name: Reelizer
  schemaVersion: 3.4.10
  timeZone: America/Los_Angeles
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: ''
  photoVolumeUid: null
  requireEmailVerification: true
volumes:
  063c95ee-112b-4ccf-adcb-3eb6a2831580:
    handle: images
    hasUrls: true
    name: Images
    settings:
      addSubfolderToRootUrl: '1'
      autoFocalPoint: ''
      bucket: $S3_BUCKET
      bucketSelectionMode: manual
      cfDistributionId: $CLOUDFRONT_DISTRIBUTION_ID
      cfPrefix: $CLOUDFRONT_PATH_PREFIX
      expires: '3 months'
      keyId: $S3_API_KEY
      makeUploadsPublic: ''
      region: $S3_REGION
      secret: $S3_SECRET
      storageClass: ''
      subfolder: images
    sortOrder: 1
    type: craft\awss3\Volume
    url: 'https://d2kj6gz9noqpfd.cloudfront.net'
