contentColumnType: integer(10)
fieldGroup: 68b8bf74-05e0-459b-8f1d-fb4f5493990b
handle: height
instructions: ''
name: Height
searchable: false
settings:
  decimals: 0
  defaultValue: null
  max: null
  min: '0'
  prefix: ''
  size: null
  suffix: in.
translationKeyFormat: null
translationMethod: none
type: craft\fields\Number
