contentColumnType: string(280)
fieldGroup: 68b8bf74-05e0-459b-8f1d-fb4f5493990b
handle: productTitle
instructions: ''
name: 'Product Title'
searchable: false
settings:
  byteLimit: null
  charLimit: 70
  code: ''
  columnType: null
  initialRows: '4'
  multiline: ''
  placeholder: ''
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
