enableVersioning: true
handle: people
name: People
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  1eac5e05-6bb4-47c3-ad67-d9f6c170d55c:
    enabledByDefault: true
    hasUrls: true
    template: ''
    uriFormat: 'people/{slug}'
type: channel
